@Aiba_HostAddress = http://localhost:5188

POST {{Aiba_HostAddress}}/api/Search
Accept: application/json
Content-Type: application/json

{
  "searchType" : "manga",
  "searchText" : "test",
  "page" : 1
}

###